### ISSUE TITLE
handle chinese charater

### ISSUE THREAD

**Issue by libedeutch** [Aalto-LeTech/greedy-string-tiling#5]
It seems this algorithm is incapable to handle Chinese characters. Is there any way I can use it to test alignment in Chinese texts? Thank you!

**Comment by teemulehtinen** [comment]
This algorithm is not very good for comparing natural texts. This package has been created for similarity checks for program code where the input is first transformed into a small set of ascii characters representing different token types in the source code. For this purpose the main concern is efficiency and supporting larger UTF character sets would make the algorithm less efficient. Therefore, there is not likely going to be support for Chinese or other non-ascii characters. I suggest you seek for other text comparison algorithms or implementations online!

**Comment by libedeutch** [comment]
Got it! Thank you very much!!!!!!!
















At 2021-08-21 13:29:18, "Teemu Lehtinen" ***@***.***> wrote:

This algorithm is not very good for comparing natural texts. This package has been created for similarity checks for program code where the input is first transformed into a small set of ascii characters representing different token types in the source code. For this purpose the main concern is efficiency and supporting larger UTF character sets would make the algorithm less efficient. Therefore, there is not likely going to be support for Chinese or other non-ascii characters. I suggest you seek for other text comparison algorithms or implementations online!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
